apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: frontend
  template:
    metadata:
      labels: 
        components: frontend
    spec:
      containers:
        - name: app-conv
          image: antonlarichev/conv-app:1.2
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "258Mi"
              cpu: "500m"
          